name: Obtener versi贸n
description: Da el nombre de la versi贸n actual, con snapshot si es para dev

inputs:
  env:  
    description: 'In which environment must this be deployed'
    required: true
    default: UAT

outputs:
  version:
    description: 'Versi贸n de la aplicaci贸n'
    value: ${{ steps.version_name.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: set version name
      id: version_name
      run: |
        output=$(bash ./.github/actions/get-version/get-version.sh)
        if [ "${{ inputs.env }}" == 'UAT' ]; then
          output="${output}-SNAPSHOT"
        fi
        echo "::set-output name=version::${output}"
      shell: bash
